export const ADD_TO_CART = "ADD_TO_CART";
export const ADD_TO_CART1 = "ADD_TO_CART1";

export const REMOVE_CART_ITEM = "REMOVE_CART_ITEM";
export const REMOVE_CART_ITEM1 = "REMOVE_CART_ITEM1";

export const UPDATE_CART_RESET = "UPDATE_CART_RESET";

export const SAVE_SHIPPING_INFO = "SAVE_SHIPPING_INFO";
