export const ALL_PRODUCT1_REQUEST = "ALL_PRODUCT1_REQUEST";
export const ALL_PRODUCT1_SUCCESS = "ALL_PRODUCT1_SUCCESS";
export const ALL_PRODUCT1_FAIL = "ALL_PRODUCT1_FAIL";
export const ALL_GUIDE_REQUEST = "ALL_GUIDE_REQUEST";
export const ALL_GUIDE_SUCCESS = "ALL_GUIDE_SUCCESS";
export const ALL_GUIDE_FAIL = "ALL_GUIDE_FAIL";

// export const ADMIN_PRODUCT_REQUEST = "ADMIN_PRODUCT_REQUEST";
// export const ADMIN_PRODUCT_SUCCESS = "ADMIN_PRODUCT_SUCCESS";
// export const ADMIN_PRODUCT_FAIL = "ADMIN_PRODUCT_FAIL";

export const NEW_PRODUCT1_REQUEST = "NEW_PRODUCT1_REQUEST";
export const NEW_PRODUCT1_SUCCESS = "NEW_PRODUC1T_SUCCESS";
export const NEW_PRODUCT1_RESET = "NEW_PRODUCT1_RESET";
export const NEW_PRODUCT1_FAIL = "NEW_PRODUCT1_FAIL";

// export const UPDATE_PRODUCT_REQUEST = "UPDATE_PRODUCT_REQUEST";
// export const UPDATE_PRODUCT_SUCCESS = "UPDATE_PRODUCT_SUCCESS";
// export const UPDATE_PRODUCT_RESET = "UPDATE_PRODUCT_RESET";
// export const UPDATE_PRODUCT_FAIL = "UPDATE_PRODUCT_FAIL";

// export const DELETE_PRODUCT_REQUEST = "DELETE_PRODUCT_REQUEST";
// export const DELETE_PRODUCT_SUCCESS = "DELETE_PRODUCT_SUCCESS";
// export const DELETE_PRODUCT_RESET = "DELETE_PRODUCT_RESET";
// export const DELETE_PRODUCT_FAIL = "DELETE_PRODUCT_FAIL";

export const PRODUCT1_DETAILS_REQUEST = "PRODUCT1_DETAILS_REQUEST";
export const PRODUCT1_DETAILS_SUCCESS = "PRODUCT1_DETAILS_SUCCESS";
export const PRODUCT1_DETAILS_FAIL = "PRODUCT1_DETAILS_FAIL";

export const NEW_REVIEW1_REQUEST = "NEW_REVIEW1_REQUEST";
export const NEW_REVIEW1_SUCCESS = "NEW_REVIEW1_SUCCESS";
export const NEW_REVIEW1_RESET = "NEW_REVIEW1_RESET";
export const NEW_REVIEW1_FAIL = "NEW_REVIEW1_FAIL";

// export const ALL_REVIEW_REQUEST = "ALL_REVIEW_REQUEST";
// export const ALL_REVIEW_SUCCESS = "ALL_REVIEW_SUCCESS";
// export const ALL_REVIEW_FAIL = "ALL_REVIEW_FAIL";

// export const DELETE_REVIEW_REQUEST = "DELETE_REVIEW_REQUEST";
// export const DELETE_REVIEW_SUCCESS = "DELETE_REVIEW_SUCCESS";
// export const DELETE_REVIEW_RESET = "DELETE_REVIEW_RESET";
// export const DELETE_REVIEW_FAIL = "DELETE_REVIEW_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";