export const VENDOR_LOGIN_REQUEST = "VENDOR_LOGIN_REQUEST";
export const VENDOR_LOGIN_SUCCESS = "VENDOR_LOGIN_SUCCESS";
export const VENDOR_LOGIN_FAIL = "VENDOR_LOGIN_FAIL";
export const VENDOR1_LOGIN_REQUEST = "VENDOR1_LOGIN_REQUEST";
export const VENDOR1_LOGIN_SUCCESS = "VENDOR1_LOGIN_SUCCESS";
export const VENDOR1_LOGIN_FAIL = "VENDOR1_LOGIN_FAIL";


export const REGISTER_VENDOR_REQUEST = "REGISTER_VENDOR_REQUEST";
export const REGISTER_VENDOR_SUCCESS = "REGISTER_VENDOR_SUCCESS";
export const REGISTER_VENDOR_FAIL = "REGISTER_VENDOR_FAIL";
export const REGISTER_VENDOR1_REQUEST = "REGISTER_VENDOR1_REQUEST";
export const REGISTER_VENDOR1_SUCCESS = "REGISTER_VENDOR1_SUCCESS";
export const REGISTER_VENDOR1_FAIL = "REGISTER_VENDOR1_FAIL";

export const LOGOUT_VENDOR_SUCCESS = "LOGOUT_VENDOR_SUCCESS";
export const LOGOUT_VENDOR_FAIL = "LOGOUT_VENDOR_FAIL";
export const LOGOUT_VENDOR1_SUCCESS = "LOGOUT_VENDOR1_SUCCESS";
export const LOGOUT_VENDOR1_FAIL = "LOGOUT_VENDOR1_FAIL";


export const UPDATE_VENDOR_PROFILE_REQUEST = "UPDATE_VENDOR_PROFILE_REQUEST";
export const UPDATE_VENDOR_PROFILE_SUCCESS = "UPDATE_VENDOR_PROFILE_SUCCESS";
export const UPDATE_VENDOR_PROFILE_RESET = "UPDATE_VENDOR_PROFILE_RESET";
export const UPDATE_VENDOR_PROFILE_FAIL = "UPDATE_VENDOR_PROFILE_FAIL";
export const UPDATE_VENDOR1_PROFILE_REQUEST = "UPDATE_VENDOR1_PROFILE_REQUEST";
export const UPDATE_VENDOR1_PROFILE_SUCCESS = "UPDATE_VENDOR1_PROFILE_SUCCESS";
export const UPDATE_VENDOR1_PROFILE_RESET = "UPDATE_VENDOR1_PROFILE_RESET";
export const UPDATE_VENDOR1_PROFILE_FAIL = "UPDATE_VENDOR1_PROFILE_FAIL";

export const UPDATE_VENDOR_PASSWORD_REQUEST = "UPDATE_VENDOR_PASSWORD_REQUEST";
export const UPDATE_VENDOR_PASSWORD_SUCCESS = "UPDATE_VENDOR_PASSWORD_SUCCESS";
export const UPDATE_VENDOR_PASSWORD_RESET = "UPDATE_VENDOR_PASSWORD_RESET";
export const UPDATE_VENDOR_PASSWORD_FAIL = "UPDATE_VENDOR_PASSWORD_FAIL";
export const UPDATE_VENDOR1_PASSWORD_REQUEST = "UPDATE_VENDOR1_PASSWORD_REQUEST";
export const UPDATE_VENDOR1_PASSWORD_SUCCESS = "UPDATE_VENDOR1_PASSWORD_SUCCESS";
export const UPDATE_VENDOR1_PASSWORD_RESET = "UPDATE_VENDOR1_PASSWORD_RESET";
export const UPDATE_VENDOR1_PASSWORD_FAIL = "UPDATE_VENDOR1_PASSWORD_FAIL";

export const FORGOT_VENDOR_PASSWORD_REQUEST = "FORGOT_VENDOR_PASSWORD_REQUEST";
export const FORGOT_VENDOR_PASSWORD_SUCCESS = "FORGOT_VENDOR_PASSWORD_SUCCESS";
export const FORGOT_VENDOR_PASSWORD_FAIL = "FORGOT_VENDOR_PASSWORD_FAIL";
export const FORGOT_VENDOR1_PASSWORD_REQUEST = "FORGOT_VENDOR1_PASSWORD_REQUEST";
export const FORGOT_VENDOR1_PASSWORD_SUCCESS = "FORGOT_VENDOR1_PASSWORD_SUCCESS";
export const FORGOT_VENDOR1_PASSWORD_FAIL = "FORGOT_VENDOR1_PASSWORD_FAIL";

export const RESET_VENDOR_PASSWORD_REQUEST = "RESET_VENDOR_PASSWORD_REQUEST";
export const RESET_VENDOR_PASSWORD_SUCCESS = "RESET_VENDOR_PASSWORD_SUCCESS";
export const RESET_VENDOR_PASSWORD_FAIL = "RESET_VENDOR_PASSWORD_FAIL";
export const RESET_VENDOR1_PASSWORD_REQUEST = "RESET_VENDOR1_PASSWORD_REQUEST";
export const RESET_VENDOR1_PASSWORD_SUCCESS = "RESET_VENDOR1_PASSWORD_SUCCESS";
export const RESET_VENDOR1_PASSWORD_FAIL = "RESET_VENDOR1_PASSWORD_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";